### ISSUE TITLE
The training steps may be not clear, got runtime error during with_sam stage

### ISSUE THREAD

**Issue by Learningm** [ashawkey/Segment-Anything-NeRF#2]
I tried the training steps mentioned in ReadMe on my own data.
`### train rgb
python main.py my_data --workspace exp_mydata --enable_cam_center 
### train sam
python main.py my_data --workspace exp_mydata --enable_cam_center  --with_sam --init_ckpt exp_mydata/checkpoints/ngp.pth --iters 5000`

I got runtime error during the second stage training, as well as some warnings:

<img width="1658" alt="issue" src="https://user-images.githubusercontent.com/13192241/234558122-346972a6-2bc0-4303-a13c-87bb1a973f42.png">

It seems the second stage did not start training, also miss some keys when loading the `init_ckpt`. Could you please figure it out? Thanks.

**Comment by dnvtmf** [comment]
When train sam, you should given another workspace, such as exp_mydata_2. 

The code will automatically load checkpoint from given workspace, until you use the option "--ckpt".
